Calculate maximum CP
BrunnerLivio/pokemongo-data-normalizer pull request #10
Opened 2017-03-31 08:33 UTC by BrunnerLivio

I added a max CP Calculator. Source for the calculation from [/u/CpMultiplier](https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/)
Fixes #9

2017-03-31 08:37 UTC, BrunnerLivio commented
@proegssilb The maxCP values are not correct at the moment. I think the problem is I did not add "IndividualAttack", "IndividualStamina" or "IndividualDefense" as described [on reddit](https://www.reddit.com/r/TheSilphRoad/comments/4t7r4d/exact_pokemon_cp_formula/). I don't know how I get these values. Do you know that? 

Also, can you go through cp-calculator.ts, if I calculated it correctly?

2017-03-31 12:58 UTC, proegssilb reviewed
All of the individual values are 0-15. So, for Max CP, you just set it to 15. 

Aside from calling MAX with one argument, and the Individual Stam/Att/Def (AKA IVs), looks great.

2017-03-31 12:58 UTC, proegssilb commented on src/core/cp-calculator/cp-calculator.ts
> +        )
Are you calling Math.max with one argument?

2017-03-31 13:33 UTC, proegssilb commented
Code speaks louder than words: https://github.com/proegssilb/pokemon-go-rankings/blob/master/generate-output.py#L48

I didn't implement the "max(..., 10)" bit there because I didn't care too much about it. The CP multiplier is brute-forced, because I didn't know about the reddit community's CPM table at the time.

2017-04-01 10:30 UTC, BrunnerLivio commented
@proegssilb still not getting the expected results. (Source for maxcp: http://www.imore.com/pokemon-go-gen-2)

Am I still missing something?

2017-04-01 13:45 UTC, proegssilb requested changes
Looks like just a couple of issues with how you call the CP Calculator. See my code comments.

EDIT: Maybe you could pass in a Pokemon object or a PokemonStats object instead of the raw stats? I'm not sure what the right amount of coupling is here.

2017-04-01 13:45 UTC, proegssilb commented on src/components/pokemon/pokemon.mapper.ts
> +            .Calculate(pokemon.stats.baseStamina, pokemon.stats.baseAttack, pokemon.stats.baseStamina);
Shouldn't this be using `pokemon.stats.baseDefense` somewhere?

2017-04-01 13:45 UTC, proegssilb commented on src/core/cp-calculator/cp-calculator.spec.ts
> +        cp = CPCalculator.Calculate(122, 155, 120);
This looks like the wrong argument order to me. I got the right answer with `cp = CPCalculator.Calculate(120, 122, 155);`.

2017-04-01 13:45 UTC, proegssilb commented on src/core/cp-calculator/cp-calculator.spec.ts
> +});
Can we add a test case for another pokemon or two? Here's one for Meganium:

it('should output the correct values for Meganium', () => {
        // source: https://rankedboost.com/pokemon-go/generation-2-tier-list/
        let cp: number;
        cp = CPCalculator.Calculate(160, 168, 202);
        expect(cp).to.equal(2227);
    });

2017-04-03 07:06 UTC, BrunnerLivio commented on src/components/pokemon/pokemon.mapper.ts
> +            .Calculate(pokemon.stats.baseStamina, pokemon.stats.baseAttack, pokemon.stats.baseStamina);
Oh, stupid mistake.

2017-04-03 07:10 UTC, BrunnerLivio commented
@proegssilb Not sure if we should use `PokemonStats` interface as parameter, because that would mean I need to import inside `core/cp-calculator` from `components/pokemon`. I don't think "core" should depend on "components".

2017-04-03 13:15 UTC, proegssilb commented
Sounds like a good reason to me.

2017-04-03 13:20 UTC, proegssilb approved these changes

2017-04-03 13:20 UTC, merged